*javax.naming.directory.AttributeInUseException* *AttributeInUseException* This exception is thrown when an operation attempts
 to add an attribute that already exists.

public class AttributeInUseException
  extends    |javax.naming.NamingException|

|javax.naming.directory.AttributeInUseException_Description|
|javax.naming.directory.AttributeInUseException_Fields|
|javax.naming.directory.AttributeInUseException_Constructors|
|javax.naming.directory.AttributeInUseException_Methods|

====================================================================================================================================================================================

*javax.naming.directory.AttributeInUseException_Constructors*
|javax.naming.directory.AttributeInUseException()|Constructs a new instance of AttributeInUseException.
|javax.naming.directory.AttributeInUseException(String)|Constructs a new instance of AttributeInUseException with  an explanation.

*javax.naming.directory.AttributeInUseException_Description*

This exception is thrown when an operation attempts to add an attribute that already exists. 

Synchronization and serialization issues that apply to NamingException apply directly here. 



*javax.naming.directory.AttributeInUseException()*

public AttributeInUseException()

Constructs a new instance of AttributeInUseException. All fields are initialized to null. 


*javax.naming.directory.AttributeInUseException(String)*

public AttributeInUseException(java.lang.String explanation)

Constructs a new instance of AttributeInUseException with an explanation. All other fields are set to null. 

    explanation - Possibly null additional detail about this exception. 

