*java.awt.print.PrinterIOException* *PrinterIOException* The PrinterIOException 

public class PrinterIOException
  extends    |java.awt.print.PrinterException|

|java.awt.print.PrinterIOException_Description|
|java.awt.print.PrinterIOException_Fields|
|java.awt.print.PrinterIOException_Constructors|
|java.awt.print.PrinterIOException_Methods|

================================================================================

*java.awt.print.PrinterIOException_Constructors*
|java.awt.print.PrinterIOException(IOException)|Constructs a new PrinterIOExcep

*java.awt.print.PrinterIOException_Methods*
|java.awt.print.PrinterIOException.getCause()|Returns the the cause of this exc
|java.awt.print.PrinterIOException.getIOException()|Returns the IOException tha

*java.awt.print.PrinterIOException_Description*

The PrinterIOException class is a subclass of 
(|java.awt.print.PrinterException|) and is used to indicate that an IO error of 
some sort has occurred while printing. 

As of release 1.4, this exception has been retrofitted to conform to the 
general purpose exception-chaining mechanism. The "IOException that terminated 
the print job" that is provided at construction time and accessed via the 
(|java.awt.print.PrinterIOException|) method is now known as the cause, and may 
be accessed via the (|java.lang.Throwable|) method, as well as the 
aforementioned "legacy method." 


*java.awt.print.PrinterIOException(IOException)*

public PrinterIOException(java.io.IOException exception)

Constructs a new PrinterIOException with the string representation of the 
specified (|java.io.IOException|) . 

    exception - the specified IOException 

*java.awt.print.PrinterIOException.getCause()*

public |java.lang.Throwable| getCause()

Returns the the cause of this exception (the IOException that terminated the 
print job). 


    Returns: the cause of this exception. 
*java.awt.print.PrinterIOException.getIOException()*

public |java.io.IOException| getIOException()

Returns the IOException that terminated the print job. 

This method predates the general-purpose exception chaining facility. The 
(|java.lang.Throwable|) method is now the preferred means of obtaining this 
information. 


    Returns: the IOException that terminated the print job. 

